import { describe, test, expect } from 'bun:test';
import { Window } from 'happy-dom';
import '@angora-js/compiler';
import { Component, signal, computed, inject } from '@angora-js/core';
import {
  renderToString,
  hydrateApplication,
  TRANSFER_STATE,
  SERVER_CONTEXT,
} from '../src/index.ts';

describe('@angora-js/server - SSR & Hydration Engine', () => {
  test('should render component to HTML string with signals and control flow', async () => {
    @Component({
      selector: 'ssr-app',
      template: `
        <div class="container">
          <h1>{{ title() }}</h1>
          <p>Count: {{ count() }}</p>
        </div>
      `,
    })
    class SsrApp {
      title = signal('Angora SSR Engine');
      count = signal(42);
    }

    const { html } = await renderToString(SsrApp, { url: '/home' });

    expect(html).toContain('<div class="container">');
    expect(html).toContain('<h1>Angora SSR Engine</h1>');
    expect(html).toContain('<p>Count: 42</p>');
  });

  test('should support TransferState across server and client', async () => {
    @Component({
      selector: 'state-app',
      template: `<div>{{ user() }}</div>`,
    })
    class StateApp {
      user = signal('Guest');
      transferState = inject(TRANSFER_STATE);

      angoraOnInit() {
        this.transferState.set('user_profile', { id: 101, name: 'Alice' });
      }
    }

    const { html, stateScript, stateJson } = await renderToString(StateApp);

    expect(stateJson).toContain('"user_profile":{"id":101,"name":"Alice"}');
    expect(stateScript).toContain('id="__ANGORA_TRANSFER_STATE__"');
  });

  test('should render via Pure String SSR without Happy-DOM when ssrRender is present', async () => {
    @Component({
      selector: 'pure-ssr-app',
      template: `
        <div class="card" [class.highlight]="isHighlight()">
          <h2>{{ name() }}</h2>
          <span class="role">{{ role() }}</span>
        </div>
      `,
      styles: [
        `
          .card {
            padding: 16px;
          }
        `,
      ],
    })
    class PureSsrApp {
      name = signal('Antigravity');
      role = signal('Core Architect');
      isHighlight = signal(true);
    }

    // Attach compiled ssrRender function as generated by Rust compiler
    (PureSsrApp as any).ɵcmp.scopeId = '_angora-pure-ssr-app';
    (PureSsrApp as any).ɵcmp.ssrRender = (ctx: any) => {
      const cls = ctx.isHighlight() ? 'card highlight' : 'card';
      return `<div class="${cls}" _angora-pure-ssr-app=""><h2><!--t-->${ctx.name()}</h2><span class="role" _angora-pure-ssr-app=""><!--t-->${ctx.role()}</span></div>`;
    };

    const res = await renderToString(PureSsrApp);

    expect(res.html).toContain('class="card highlight"');
    expect(res.html).toContain('_angora-pure-ssr-app=""');
    expect(res.html).toContain('<!--t-->Antigravity');
    expect(res.html).toContain('<!--t-->Core Architect');
    expect(res.stylesHtml).toContain('data-angora-scope="_angora-pure-ssr-app"');
  });

  test('should hydrate server-rendered application non-destructively in container', () => {
    const window = new Window();
    const prevDoc = (globalThis as any).document;
    (globalThis as any).document = window.document;
    try {
      const container = window.document.createElement('div');
      container.id = 'app';
      container.innerHTML = `<div class="counter" _angora-counter=""><p>Count: <!--t-->10</p><button>Increment</button></div>`;
      window.document.body.appendChild(container);

      const initialElement = container.firstElementChild!;

      @Component({
        selector: 'counter-app',
        template: `<div class="counter">
          <p>
            Count:
            <!--t-->{{ count() }}
          </p>
          <button (click)="inc()">Increment</button>
        </div>`,
      })
      class CounterApp {
        count = signal(10);
        inc() {
          this.count.update(n => n + 1);
        }
      }

      (CounterApp as any).ɵcmp.render = (ctx: any, inj: any, rootNode?: Node) => {
        // Binds to rootNode when hydrating
        const root =
          rootNode && rootNode.nodeType === 1 ? rootNode : window.document.createElement('div');
        return [root];
      };

      const app = hydrateApplication(CounterApp, container as any);
      expect(app).toBeInstanceOf(CounterApp);

      // Ensure the server element is preserved in place
      expect(container.firstElementChild).toBe(initialElement);
    } finally {
      (globalThis as any).document = prevDoc;
    }
  });
});
